###############################################################################
################################# INSTALL #####################################
###############################################################################
- name: Read package checksum file
  local_action: stat path="{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  become: no
  run_once: true
  register: consul_checksum
  tags:
    - installation
    - consul

- name: Download package checksum file
  local_action: get_url url="{{ consul_checksum_file_url }}" dest="{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  become: no
  run_once: true
  tags:
    - installation
    - consul
  when: not consul_checksum.stat.exists | bool

- name: Read package checksum
  local_action: shell grep "{{ consul_pkg }}" "{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS" | awk '{print $1}'
  become: no
  run_once: true
  register: consul_sha256
  tags:
    - installation
    - consul

- name: Check Consul package file
  local_action: stat path="{{ role_path }}/files/{{ consul_pkg }}"
  become: no
  run_once: true
  register: consul_package
  tags:
    - installation
    - consul

- name: Download Consul package
  local_action: get_url url="{{ consul_zip_url }}" dest="{{ role_path }}/files/{{ consul_pkg }}" checksum="sha256:{{ consul_sha256.stdout }}" timeout="42"
  become: no
  run_once: true
  tags:
    - installation
    - consul
  when: not consul_package.stat.exists | bool

- name: Unarchive Consul package
  local_action: unarchive src="{{ role_path }}/files/{{ consul_pkg }}" dest="{{ role_path }}/files/" creates="{{ role_path }}/files/consul"
  become: no
  run_once: true
  tags:
    - installation
    - consul

- name: Install Consul
  unarchive:
#    src: "{{ role_path }}/files/consul"
    src: "{{ consul_pkg }}"
    dest: "{{ consul_install_path }}"
    owner: "{{ consul_owner }}"
    group: "{{ consul_group }}"
#    mode: 0755
  become: yes
  tags:
    - installation
    - consul

- name: Cleanup
  local_action: file path="{{ item }}" state="absent"
  become: no
  with_fileglob: "{{ role_path }}/files/consul"
  run_once: true
  tags:
    - installation
    - consul
