#!/usr/bin/env ansible-playbook -i inventory.ini --skip-tags=consul-servers,bootstrap,vault
---
- hosts: bramble
  gather_facts: true
  remote_user: pi
  become: yes
  become_user: root
  roles:
    - utils
    - { role: dnsmasq, consul_dns_domain: bramble.local, consul_dc: alpha }
  tags:
    - bramble
    - bootstrap

- name: setup the consul servers
  hosts: consul
  gather_facts: true
  remote_user: pi
  roles:
    - { role: consul, consul_is_server: yes, consul_dc: alpha, consul_bootstrap_expect: "{{ groups['baron'] | length }}", consul_ui_enabled: yes }
  tags:
    - consul
    - consul-servers

- name: setup the baron
  hosts: baron
  gather_facts: true
  remote_user: pi
  roles:
    - { role: vault, vault_datacenter: alpha }
    - { role: nomad, nomad_is_server: yes, nomad_dc: alpha }
    # - prometheus
    # - grafana
  tags:
    - baron
    - vault
    - nomad
    - prometheus
    - grafana

- name: setup the folowers
  hosts: followers
  gather_facts: true
  remote_user: pi
  roles:
    - { role: docker }
    - { role: consul, consul_dc: alpha }
    - { role: nomad, nomad_dc: alpha }
  tags:
    - followers
    - consul
    - nomad
