---
- name: install check scripts
  template:
    src: check-service-active.j2
    dest: /usr/local/bin/check-service-active
    mode: u=rwx,g=rx,o=rx
  tags:
    - utils

- name: Install tools
  apt:
    name: htop,dnsutils,telnet,vim
    update_cache: yes
  tags:
    - utils
