###############################################################################
################################# INSTALL #####################################
###############################################################################
- name: Read package checksum file
  local_action: stat path="{{ role_path }}/files/vault_{{ vault_version }}_SHA256SUMS"
  become: no
  run_once: true
  register: vault_checksum
  tags:
    - installation
    - vault

- name: Download package checksum file
  local_action: get_url url="{{ vault_checksum_file_url }}" dest="{{ role_path }}/files/vault_{{ vault_version }}_SHA256SUMS" validate_certs=no
  become: no
  run_once: true
  tags:
    - installation
    - vault
  when: not vault_checksum.stat.exists | bool

- name: Read package checksum
  local_action: shell grep "{{ vault_pkg }}" "{{ role_path }}/files/vault_{{ vault_version }}_SHA256SUMS" | awk '{print $1}'
  become: no
  run_once: true
  register: vault_sha256
  tags:
    - installation
    - vault

- name: Check Vault package file
  local_action: stat path="{{ role_path }}/files/{{ vault_pkg }}"
  become: no
  run_once: true
  register: vault_package
  tags:
    - installation
    - vault

- name: Download Vault package
  local_action: get_url url="{{ vault_zip_url }}" dest="{{ role_path }}/files/{{ vault_pkg }}" checksum="sha256:{{ vault_sha256.stdout }}" timeout="42" validate_certs=no
  become: no
  run_once: true
  tags:
    - installation
    - vault
  when: not vault_package.stat.exists | bool

- name: Unarchive Vault package
  local_action: unarchive src="{{ role_path }}/files/{{ vault_pkg }}" dest="{{ role_path }}/files/" creates="{{ role_path }}/files/vault"
  become: no
  run_once: true
  tags:
    - installation
    - vault

- name: Install Vault
  copy:
    src: "{{ role_path }}/files/vault"
    dest: "{{ vault_install_path }}/vault"
    owner: "{{ vault_owner }}"
    group: "{{ vault_group }}"
    mode: 0755
  become: yes
  tags:
    - installation
    - vault

- name: Cleanup
  local_action: file path="{{ item }}" state="absent"
  become: no
  with_fileglob: "{{ role_path }}/files/vault"
  run_once: true
  tags:
    - installation
    - vault

